[2025-05-18T20:45:57.692+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eod_stock_prices_dag.trigger_postgres_to_duckdb manual__2025-05-18T20:45:38.673535+00:00 [queued]>
[2025-05-18T20:45:57.711+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eod_stock_prices_dag.trigger_postgres_to_duckdb manual__2025-05-18T20:45:38.673535+00:00 [queued]>
[2025-05-18T20:45:57.712+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-18T20:45:57.820+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_postgres_to_duckdb> on 2025-05-18 20:45:38.673535+00:00
[2025-05-18T20:45:57.834+0000] {standard_task_runner.py:60} INFO - Started process 746 to run task
[2025-05-18T20:45:57.840+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'eod_stock_prices_dag', 'trigger_postgres_to_duckdb', 'manual__2025-05-18T20:45:38.673535+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/eod_dag.py', '--cfg-path', '/tmp/tmpxvtskvvz']
[2025-05-18T20:45:57.844+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask trigger_postgres_to_duckdb
[2025-05-18T20:45:57.937+0000] {task_command.py:423} INFO - Running <TaskInstance: eod_stock_prices_dag.trigger_postgres_to_duckdb manual__2025-05-18T20:45:38.673535+00:00 [running]> on host b06d64da5f51
[2025-05-18T20:45:58.166+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eod_stock_prices_dag' AIRFLOW_CTX_TASK_ID='trigger_postgres_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T20:45:38.673535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T20:45:38.673535+00:00'
[2025-05-18T20:45:58.203+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 165, in execute
    dag_run = trigger_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api/common/trigger_dag.py", line 122, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id postgres_to_duckdb not found in DagModel
[2025-05-18T20:45:58.210+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=eod_stock_prices_dag, task_id=trigger_postgres_to_duckdb, execution_date=20250518T204538, start_date=20250518T204557, end_date=20250518T204558
[2025-05-18T20:45:58.237+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task trigger_postgres_to_duckdb (Dag id postgres_to_duckdb not found in DagModel; 746)
[2025-05-18T20:45:58.298+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-18T20:45:58.333+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
