[2025-05-19T20:27:05.524+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T20:27:00.043219+00:00 [queued]>
[2025-05-19T20:27:05.539+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T20:27:00.043219+00:00 [queued]>
[2025-05-19T20:27:05.540+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-19T20:27:05.570+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transfer_to_duckdb> on 2025-05-19 20:27:00.043219+00:00
[2025-05-19T20:27:05.584+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2025-05-19T20:27:05.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_duckdb', 'transfer_to_duckdb', 'manual__2025-05-19T20:27:00.043219+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_duck.py', '--cfg-path', '/tmp/tmp9dze_xfq']
[2025-05-19T20:27:05.594+0000] {standard_task_runner.py:88} INFO - Job 93: Subtask transfer_to_duckdb
[2025-05-19T20:27:05.691+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T20:27:00.043219+00:00 [running]> on host d4bc4308f533
[2025-05-19T20:27:05.838+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='transfer_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T20:27:00.043219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T20:27:00.043219+00:00'
[2025-05-19T20:27:05.876+0000] {logging_mixin.py:188} INFO - Connecting to DuckDB at /opt/***/data/stock_data.duckdb with UID=50000, GID=0
[2025-05-19T20:27:05.883+0000] {logging_mixin.py:188} INFO - Error connecting to DuckDB: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied
[2025-05-19T20:27:05.884+0000] {logging_mixin.py:188} INFO - Trying alternate approach with read_only=False
[2025-05-19T20:27:05.887+0000] {logging_mixin.py:188} INFO - Alternate approach also failed: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied
[2025-05-19T20:27:05.888+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/postgres_to_duck.py", line 41, in transfer_to_duckdb
    con = duckdb.connect(db_path)
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_duck.py", line 73, in transfer_to_duckdb
    raise e2
  File "/opt/airflow/dags/postgres_to_duck.py", line 61, in transfer_to_duckdb
    con = duckdb.connect(db_path, read_only=False)
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied
[2025-05-19T20:27:05.905+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=postgres_to_duckdb, task_id=transfer_to_duckdb, execution_date=20250519T202700, start_date=20250519T202705, end_date=20250519T202705
[2025-05-19T20:27:05.923+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 93 for task transfer_to_duckdb (IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied; 87)
[2025-05-19T20:27:05.968+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-19T20:27:06.002+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
