[2025-05-23T22:55:33.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T22:55:33.368+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-23T22:55:28.430368+00:00 [queued]>
[2025-05-23T22:55:33.406+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-23T22:55:28.430368+00:00 [queued]>
[2025-05-23T22:55:33.408+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-05-23T22:55:33.441+0000] {taskinstance.py:2907} INFO - Executing <Task(PythonOperator): transfer_to_duckdb> on 2025-05-23 22:55:28.430368+00:00
[2025-05-23T22:55:33.457+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-23T22:55:33.461+0000] {standard_task_runner.py:72} INFO - Started process 321 to run task
[2025-05-23T22:55:33.464+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_duckdb', 'transfer_to_duckdb', 'manual__2025-05-23T22:55:28.430368+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_duckdb.py', '--cfg-path', '/tmp/tmpn2lew4xq']
[2025-05-23T22:55:33.468+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask transfer_to_duckdb
[2025-05-23T22:55:33.598+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-23T22:55:28.430368+00:00 [running]> on host c5b8990b83b7
[2025-05-23T22:55:33.874+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='transfer_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T22:55:28.430368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T22:55:28.430368+00:00'
[2025-05-23T22:55:33.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T22:55:33.880+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T22:55:33.881+0000] {logging_mixin.py:190} INFO - Current task name:transfer_to_duckdb state:running start_date:2025-05-23 22:55:33.371561+00:00
[2025-05-23T22:55:33.882+0000] {logging_mixin.py:190} INFO - Dag name:postgres_to_duckdb and current dag run status:running
[2025-05-23T22:55:33.884+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-23T22:55:33.968+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_to_duckdb.py", line 22, in transfer_data_to_duckdb
    conn = duckdb.connect(duckdb_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_prices.duckdb": Permission denied
[2025-05-23T22:55:34.008+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T22:55:34.009+0000] {logging_mixin.py:190} INFO - Task start:2025-05-23 22:55:33.371561+00:00 end:2025-05-23 22:55:34.006471+00:00 duration:0.63491
[2025-05-23T22:55:34.011+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transfer_to_duckdb> dag:<DAG: postgres_to_duckdb> dagrun:<DagRun postgres_to_duckdb @ 2025-05-23 22:55:28.430368+00:00: manual__2025-05-23T22:55:28.430368+00:00, state:running, queued_at: 2025-05-23 22:55:28.479765+00:00. externally triggered: True>
[2025-05-23T22:55:34.012+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Cannot open file "/opt/***/data/stock_prices.duckdb": Permission denied
[2025-05-23T22:55:34.013+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=postgres_to_duckdb, task_id=transfer_to_duckdb, run_id=manual__2025-05-23T22:55:28.430368+00:00, execution_date=20250523T225528, start_date=20250523T225533, end_date=20250523T225534
[2025-05-23T22:55:34.150+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-23T22:55:34.152+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task transfer_to_duckdb (IO Error: Cannot open file "/opt/***/data/stock_prices.duckdb": Permission denied; 321)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_to_duckdb.py", line 22, in transfer_data_to_duckdb
    conn = duckdb.connect(duckdb_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_prices.duckdb": Permission denied
[2025-05-23T22:55:34.206+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T22:55:34.261+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T22:55:34.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
