[2025-05-20T17:31:42.854+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T17:31:42.903+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag manual__2025-05-20T17:31:13.991433+00:00 [queued]>
[2025-05-20T17:31:42.925+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag manual__2025-05-20T17:31:13.991433+00:00 [queued]>
[2025-05-20T17:31:42.995+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-05-20T17:31:43.025+0000] {taskinstance.py:2907} INFO - Executing <Task(TriggerDagRunOperator): trigger_duckdb_dag> on 2025-05-20 17:31:13.991433+00:00
[2025-05-20T17:31:43.042+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T17:31:43.047+0000] {standard_task_runner.py:72} INFO - Started process 117 to run task
[2025-05-20T17:31:43.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_eod_data', 'trigger_duckdb_dag', 'manual__2025-05-20T17:31:13.991433+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/eod_data_pipeline.py', '--cfg-path', '/tmp/tmp7hsd3fwi']
[2025-05-20T17:31:43.053+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask trigger_duckdb_dag
[2025-05-20T17:31:43.177+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_eod_data.trigger_duckdb_dag manual__2025-05-20T17:31:13.991433+00:00 [running]> on host 00b3251bdfc2
[2025-05-20T17:31:43.802+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_eod_data' AIRFLOW_CTX_TASK_ID='trigger_duckdb_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T17:31:13.991433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T17:31:13.991433+00:00'
[2025-05-20T17:31:43.804+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-20T17:31:43.805+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-20T17:31:43.806+0000] {logging_mixin.py:190} INFO - Current task name:trigger_duckdb_dag state:running start_date:2025-05-20 17:31:42.905212+00:00
[2025-05-20T17:31:43.807+0000] {logging_mixin.py:190} INFO - Dag name:fetch_eod_data and current dag run status:running
[2025-05-20T17:31:43.808+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-20T17:31:43.953+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:32:43.980+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:33:44.012+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:34:44.032+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:35:44.053+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:36:44.077+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-20 17:31:43.809569+00:00 to become allowed state ['success'] ...
[2025-05-20T17:37:44.134+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-20T17:37:44.173+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-20T17:37:44.175+0000] {logging_mixin.py:190} INFO - Task start:2025-05-20 17:31:42.905212+00:00 end:2025-05-20 17:37:44.169818+00:00 duration:361.264606
[2025-05-20T17:37:44.176+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_duckdb_dag> dag:<DAG: fetch_eod_data> dagrun:<DagRun fetch_eod_data @ 2025-05-20 17:31:13.991433+00:00: manual__2025-05-20T17:31:13.991433+00:00, state:running, queued_at: 2025-05-20 17:31:14.595518+00:00. externally triggered: True>
[2025-05-20T17:37:44.177+0000] {logging_mixin.py:190} INFO - Failure caused by postgres_to_duckdb failed with failed states failed
[2025-05-20T17:37:44.178+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_eod_data, task_id=trigger_duckdb_dag, run_id=manual__2025-05-20T17:31:13.991433+00:00, execution_date=20250520T173113, start_date=20250520T173142, end_date=20250520T173744
[2025-05-20T17:37:44.325+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-20T17:37:44.327+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task trigger_duckdb_dag (postgres_to_duckdb failed with failed states failed; 117)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-20T17:37:44.403+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T17:37:44.468+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T17:37:44.473+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
