[2025-05-19T19:44:07.648+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T19:44:04.371211+00:00 [queued]>
[2025-05-19T19:44:07.670+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T19:44:04.371211+00:00 [queued]>
[2025-05-19T19:44:07.671+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-19T19:44:07.701+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transfer_to_duckdb> on 2025-05-19 19:44:04.371211+00:00
[2025-05-19T19:44:07.714+0000] {standard_task_runner.py:60} INFO - Started process 107 to run task
[2025-05-19T19:44:07.720+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_duckdb', 'transfer_to_duckdb', 'manual__2025-05-19T19:44:04.371211+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_duck.py', '--cfg-path', '/tmp/tmpqjezqdkq']
[2025-05-19T19:44:07.723+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask transfer_to_duckdb
[2025-05-19T19:44:07.829+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T19:44:04.371211+00:00 [running]> on host 57ebccafb730
[2025-05-19T19:44:08.060+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='transfer_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T19:44:04.371211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T19:44:04.371211+00:00'
[2025-05-19T19:44:08.189+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_duck.py", line 23, in transfer_to_duckdb
    con = duckdb.connect("/opt/airflow/data/stock_data.duckdb")
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied
[2025-05-19T19:44:08.214+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=postgres_to_duckdb, task_id=transfer_to_duckdb, execution_date=20250519T194404, start_date=20250519T194407, end_date=20250519T194408
[2025-05-19T19:44:08.247+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 78 for task transfer_to_duckdb (IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": Permission denied; 107)
[2025-05-19T19:44:08.296+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-19T19:44:08.333+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
