[2025-05-20T17:31:48.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T17:31:48.251+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-20T17:31:43.809569+00:00 [queued]>
[2025-05-20T17:31:48.266+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-20T17:31:43.809569+00:00 [queued]>
[2025-05-20T17:31:48.269+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-05-20T17:31:48.296+0000] {taskinstance.py:2907} INFO - Executing <Task(PythonOperator): transfer_to_duckdb> on 2025-05-20 17:31:43.809569+00:00
[2025-05-20T17:31:48.313+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T17:31:48.316+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_duckdb', 'transfer_to_duckdb', 'manual__2025-05-20T17:31:43.809569+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_duckdb.py', '--cfg-path', '/tmp/tmprvrc9wmr']
[2025-05-20T17:31:48.317+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2025-05-20T17:31:48.318+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask transfer_to_duckdb
[2025-05-20T17:31:48.425+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-20T17:31:43.809569+00:00 [running]> on host 00b3251bdfc2
[2025-05-20T17:31:49.057+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='transfer_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T17:31:43.809569+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T17:31:43.809569+00:00'
[2025-05-20T17:31:49.059+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-20T17:31:49.060+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-20T17:31:49.061+0000] {logging_mixin.py:190} INFO - Current task name:transfer_to_duckdb state:running start_date:2025-05-20 17:31:48.252829+00:00
[2025-05-20T17:31:49.062+0000] {logging_mixin.py:190} INFO - Dag name:postgres_to_duckdb and current dag run status:running
[2025-05-20T17:31:49.064+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-20T17:31:49.159+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_to_duckdb.py", line 25, in transfer_data_to_duckdb
    conn = duckdb.connect(duckdb_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stocks.duckdb": Permission denied
[2025-05-20T17:31:49.194+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-20T17:31:49.196+0000] {logging_mixin.py:190} INFO - Task start:2025-05-20 17:31:48.252829+00:00 end:2025-05-20 17:31:49.194285+00:00 duration:0.941456
[2025-05-20T17:31:49.197+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transfer_to_duckdb> dag:<DAG: postgres_to_duckdb> dagrun:<DagRun postgres_to_duckdb @ 2025-05-20 17:31:43.809569+00:00: manual__2025-05-20T17:31:43.809569+00:00, state:running, queued_at: 2025-05-20 17:31:43.870824+00:00. externally triggered: True>
[2025-05-20T17:31:49.198+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Cannot open file "/opt/***/data/stocks.duckdb": Permission denied
[2025-05-20T17:31:49.199+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_to_duckdb, task_id=transfer_to_duckdb, run_id=manual__2025-05-20T17:31:43.809569+00:00, execution_date=20250520T173143, start_date=20250520T173148, end_date=20250520T173149
[2025-05-20T17:31:49.331+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-20T17:31:49.332+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task transfer_to_duckdb (IO Error: Cannot open file "/opt/***/data/stocks.duckdb": Permission denied; 121)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_to_duckdb.py", line 25, in transfer_data_to_duckdb
    conn = duckdb.connect(duckdb_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stocks.duckdb": Permission denied
[2025-05-20T17:31:49.381+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T17:31:49.425+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T17:31:49.430+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
