[2025-05-19T13:50:11.280+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T13:50:04.969265+00:00 [queued]>
[2025-05-19T13:50:11.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T13:50:04.969265+00:00 [queued]>
[2025-05-19T13:50:11.297+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-19T13:50:11.328+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transfer_to_duckdb> on 2025-05-19 13:50:04.969265+00:00
[2025-05-19T13:50:11.340+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2025-05-19T13:50:11.346+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_duckdb', 'transfer_to_duckdb', 'manual__2025-05-19T13:50:04.969265+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_duck.py', '--cfg-path', '/tmp/tmpy7519buf']
[2025-05-19T13:50:11.349+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask transfer_to_duckdb
[2025-05-19T13:50:11.448+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_to_duckdb.transfer_to_duckdb manual__2025-05-19T13:50:04.969265+00:00 [running]> on host c7e0100e2166
[2025-05-19T13:50:11.599+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='transfer_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T13:50:04.969265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T13:50:04.969265+00:00'
[2025-05-19T13:50:11.643+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_duck.py", line 18, in transfer_to_duckdb
    con = duckdb.connect("/opt/airflow/data/stock_data.duckdb")
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": No such file or directory
[2025-05-19T13:50:11.664+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=postgres_to_duckdb, task_id=transfer_to_duckdb, execution_date=20250519T135004, start_date=20250519T135011, end_date=20250519T135011
[2025-05-19T13:50:11.686+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task transfer_to_duckdb (IO Error: Cannot open file "/opt/***/data/stock_data.duckdb": No such file or directory; 88)
[2025-05-19T13:50:11.721+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-19T13:50:11.756+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
