[2025-05-23T22:38:52.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T22:38:52.334+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T22:38:52.359+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T22:38:52.361+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-05-23T22:38:52.394+0000] {taskinstance.py:2907} INFO - Executing <Task(TriggerDagRunOperator): trigger_duckdb_dag> on 2025-05-22 00:00:00+00:00
[2025-05-23T22:38:52.413+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-23T22:38:52.418+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2025-05-23T22:38:52.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_eod_data', 'trigger_duckdb_dag', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/eod_data_pipeline.py', '--cfg-path', '/tmp/tmp04ucqv8s']
[2025-05-23T22:38:52.420+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask trigger_duckdb_dag
[2025-05-23T22:38:52.535+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [running]> on host c5b8990b83b7
[2025-05-23T22:38:53.282+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_eod_data' AIRFLOW_CTX_TASK_ID='trigger_duckdb_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T22:38:53.285+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T22:38:53.286+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T22:38:53.288+0000] {logging_mixin.py:190} INFO - Current task name:trigger_duckdb_dag state:running start_date:2025-05-23 22:38:52.335785+00:00
[2025-05-23T22:38:53.289+0000] {logging_mixin.py:190} INFO - Dag name:fetch_eod_data and current dag run status:running
[2025-05-23T22:38:53.290+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-23T22:38:53.545+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-23 22:38:53.291784+00:00 to become allowed state ['success'] ...
[2025-05-23T22:39:53.608+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-23T22:39:53.625+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T22:39:53.627+0000] {logging_mixin.py:190} INFO - Task start:2025-05-23 22:38:52.335785+00:00 end:2025-05-23 22:39:53.623279+00:00 duration:61.287494
[2025-05-23T22:39:53.629+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_duckdb_dag> dag:<DAG: fetch_eod_data> dagrun:<DagRun fetch_eod_data @ 2025-05-22 00:00:00+00:00: scheduled__2025-05-22T00:00:00+00:00, state:running, queued_at: 2025-05-23 22:38:24.638494+00:00. externally triggered: False>
[2025-05-23T22:39:53.630+0000] {logging_mixin.py:190} INFO - Failure caused by postgres_to_duckdb failed with failed states failed
[2025-05-23T22:39:53.631+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=fetch_eod_data, task_id=trigger_duckdb_dag, run_id=scheduled__2025-05-22T00:00:00+00:00, execution_date=20250522T000000, start_date=20250523T223852, end_date=20250523T223953
[2025-05-23T22:39:53.746+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-23T22:39:53.748+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task trigger_duckdb_dag (postgres_to_duckdb failed with failed states failed; 111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-23T22:39:53.824+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T22:39:53.867+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T22:39:53.873+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-23T23:10:16.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T23:10:16.936+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T23:10:16.958+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T23:10:16.959+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-05-23T23:10:16.996+0000] {taskinstance.py:2907} INFO - Executing <Task(TriggerDagRunOperator): trigger_duckdb_dag> on 2025-05-22 00:00:00+00:00
[2025-05-23T23:10:17.014+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-23T23:10:17.017+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_eod_data', 'trigger_duckdb_dag', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/eod_data_pipeline.py', '--cfg-path', '/tmp/tmpv7f6chs5']
[2025-05-23T23:10:17.019+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-05-23T23:10:17.019+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask trigger_duckdb_dag
[2025-05-23T23:10:17.125+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_eod_data.trigger_duckdb_dag scheduled__2025-05-22T00:00:00+00:00 [running]> on host a160e78386d6
[2025-05-23T23:10:17.878+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_eod_data' AIRFLOW_CTX_TASK_ID='trigger_duckdb_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T23:10:17.881+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T23:10:17.883+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T23:10:17.885+0000] {logging_mixin.py:190} INFO - Current task name:trigger_duckdb_dag state:running start_date:2025-05-23 23:10:16.937664+00:00
[2025-05-23T23:10:17.885+0000] {logging_mixin.py:190} INFO - Dag name:fetch_eod_data and current dag run status:running
[2025-05-23T23:10:17.886+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-23T23:10:18.040+0000] {trigger_dagrun.py:257} INFO - Waiting for postgres_to_duckdb on 2025-05-23 23:10:17.888244+00:00 to become allowed state ['success'] ...
[2025-05-23T23:11:18.083+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-23T23:11:18.097+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T23:11:18.098+0000] {logging_mixin.py:190} INFO - Task start:2025-05-23 23:10:16.937664+00:00 end:2025-05-23 23:11:18.095841+00:00 duration:61.158177
[2025-05-23T23:11:18.099+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_duckdb_dag> dag:<DAG: fetch_eod_data> dagrun:<DagRun fetch_eod_data @ 2025-05-22 00:00:00+00:00: scheduled__2025-05-22T00:00:00+00:00, state:running, queued_at: 2025-05-23 23:09:48.055777+00:00. externally triggered: False>
[2025-05-23T23:11:18.100+0000] {logging_mixin.py:190} INFO - Failure caused by postgres_to_duckdb failed with failed states failed
[2025-05-23T23:11:18.101+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=fetch_eod_data, task_id=trigger_duckdb_dag, run_id=scheduled__2025-05-22T00:00:00+00:00, execution_date=20250522T000000, start_date=20250523T231016, end_date=20250523T231118
[2025-05-23T23:11:18.155+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-23T23:11:18.157+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task trigger_duckdb_dag (postgres_to_duckdb failed with failed states failed; 143)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: postgres_to_duckdb failed with failed states failed
[2025-05-23T23:11:18.215+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T23:11:18.249+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T23:11:18.254+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
